# Generated by Django 4.2.7 on 2023-12-07 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle_driver_app', '0002_rename_nk_conytact_driver_nk_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='vehiclerepair',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='vehiclerepair',
            name='is_approved',
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_type', models.CharField(max_length=250)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(max_length=250)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='maintenance',
            name='approval_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='approval_maintenance', to='vehicle_driver_app.approval'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclerepair',
            name='approval_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='approval_repair', to='vehicle_driver_app.approval'),
            preserve_default=False,
        ),
    ]
