# Generated by Django 4.2.7 on 2023-12-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver_app', '0003_remove_maintenance_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_condition',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
