# Generated by Django 4.2.7 on 2023-12-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver_app', '0005_remove_maintenance_maintenance_type_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='approval_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_maintenance', to='vehicle_driver_app.approval'),
        ),
    ]
