# Generated by Django 4.2.7 on 2023-12-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver_app', '0006_alter_maintenance_approval_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approval_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerepair',
            name='repair_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
