# Generated by Django 4.2.7 on 2023-12-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver_app', '0008_alter_vehiclerepair_approval_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='driverlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='driverlog',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='driverlog',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='driverlog',
            name='total_number_passengers',
        ),
        migrations.AddField(
            model_name='driverlog',
            name='is_arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driverlog',
            name='datetime_daparture',
            field=models.DateField(),
        ),
    ]
