# Generated by Django 4.2.7 on 2023-12-15 20:56

from django.db import migrations, models
import vehicle_driver_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver_app', '0009_remove_driverlog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=vehicle_driver_app.models.upload_to),
        ),
    ]
