# Generated by Django 4.2.7 on 2023-12-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver_app', '0010_driver_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='relationship',
            field=models.CharField(max_length=50),
        ),
    ]
