# Generated by Django 4.2.7 on 2023-12-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver_app', '0011_alter_driver_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='image_url',
            new_name='image',
        ),
    ]
