# Generated by Django 4.2.7 on 2023-12-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver_app', '0012_rename_image_url_driver_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlog',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
