# Generated by Django 4.2.7 on 2023-12-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver_app', '0014_invoice_maintenance_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approved_by',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
