# Generated by Django 4.2.7 on 2023-12-21 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver_app', '0015_invoice_approved_by_invoice_invoice_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerepair',
            name='invoice_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_repair', to='vehicle_driver_app.invoice'),
        ),
    ]
