# Generated by Django 4.2.7 on 2023-12-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver_app', '0016_vehiclerepair_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
