# Generated by Django 4.2.7 on 2023-12-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_schedule_seats_available_alter_schedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='depart_time',
            field=models.TimeField(null=True),
        ),
    ]
