# Generated by Django 4.2.7 on 2023-12-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
