# Generated by Django 4.2.7 on 2023-12-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_accounting', '0004_alter_booking_seat_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
