# Generated by Django 4.2.7 on 2023-12-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_accounting', '0005_booking_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
    ]
