# Generated by Django 4.2.7 on 2023-12-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_accounting', '0006_remove_booking_payment_status_booking_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadingbooking',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='loadingbooking',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='loadingbooking',
            name='loading_date',
            field=models.DateField(null=True),
        ),
    ]
