# Generated by Django 4.2.7 on 2023-12-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_accounting', '0007_remove_loadingbooking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingbooking',
            name='driver_name',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
