# Generated by Django 4.2.7 on 2023-12-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_accounting', '0008_loadingbooking_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
