# Generated by Django 4.2.7 on 2023-12-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_accounting', '0009_booking_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
