# Generated by Django 4.2.7 on 2023-12-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_accounting', '0011_currentbalance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentbalance',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
